server:
  port: 0
  
spring:
  application:
    name: kafka-consumer
  cloud:
    stream:
      bindings:
        consumerInput:                        # you can write here what you want! 
          destination: topicMessage
          content-type: application/json
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost